import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
	selector: 'app-login',
	imports: [MatButtonModule, MatCardModule, MatFormFieldModule, MatIconModule, MatInputModule, MatProgressSpinnerModule, ReactiveFormsModule, RouterLink],
	template: `<main class="login"><section class="login__brand"><img src="/images/pass-portal-mark.svg" alt="Pass Portal" /><p class="eyebrow">Pass Portal</p><h1>Control migratorio proactivo</h1><p>Una vista clara para anticipar vencimientos, restricciones y decisiones operativas.</p><ul class="benefits"><li><mat-icon>notifications_active</mat-icon><span><strong>Alertas proactivas</strong><small>Anticipa vencimientos antes de que se conviertan en problemas.</small></span></li><li><mat-icon>badge</mat-icon><span><strong>Fichas dinámicas</strong><small>Consulta el historial esencial desde una sola vista.</small></span></li><li><mat-icon>gavel</mat-icon><span><strong>Obligaciones y arraigos</strong><small>Da seguimiento a cada restricción con claridad.</small></span></li></ul><span class="login__footer">Entorno de demostración con datos ficticios</span></section><section class="login__form"><div class="form-card"><div class="brand"><img src="/images/pass-portal-mark.svg" alt="" /><div><strong>Pass Portal</strong><span>Gestión migratoria</span></div></div><h2>Iniciar sesión</h2><p>Accede al panel de control migratorio.</p><form [formGroup]="form" (ngSubmit)="entrar()"><mat-form-field appearance="outline"><mat-label>Usuario</mat-label><input matInput formControlName="usuario" autocomplete="username" />@if (form.controls.usuario.invalid && form.controls.usuario.touched) { <mat-error>Ingresa tu usuario.</mat-error> }</mat-form-field><mat-form-field appearance="outline"><mat-label>Contraseña</mat-label><input matInput [type]="mostrarPassword() ? 'text' : 'password'" formControlName="password" autocomplete="current-password" /><button mat-icon-button matSuffix type="button" [attr.aria-label]="mostrarPassword() ? 'Ocultar contraseña' : 'Mostrar contraseña'" (click)="mostrarPassword.set(!mostrarPassword())"><mat-icon>{{ mostrarPassword() ? 'visibility_off' : 'visibility' }}</mat-icon></button>@if (form.controls.password.invalid && form.controls.password.touched) { <mat-error>Ingresa tu contraseña.</mat-error> }</mat-form-field>@if (error()) { <div class="error" role="alert"><mat-icon>error</mat-icon>{{ error() }}</div> }<button mat-flat-button class="submit" type="submit" [disabled]="cargando()">@if (cargando()) { <mat-spinner diameter="20" aria-label="Iniciando sesión" /> } @else { Ingresar }</button><p class="help">¿Problemas para ingresar? Contacta al administrador del sistema.</p><a routerLink="/register">Crear cuenta normal</a></form></div></section></main>`,
	styles: [`.login{min-height:100dvh;display:grid;grid-template-columns:minmax(300px,.9fr) minmax(380px,1.1fr);background:var(--mat-sys-surface)}.login__brand{display:flex;flex-direction:column;justify-content:center;padding:clamp(32px,8vw,110px);color:#fff;background:linear-gradient(145deg,var(--pp-marino-profundo),var(--pp-marino) 58%,#0e7490)}.login__brand>img{width:72px;height:72px;margin-bottom:28px}.eyebrow{text-transform:uppercase;letter-spacing:.14em;font-weight:700;color:var(--pp-turquesa);margin:0 0 12px}.login__brand h1{font-size:clamp(32px,4vw,56px);line-height:1.05;max-width:560px;margin:0 0 20px}.login__brand>p:not(.eyebrow){max-width:470px;color:#d9f5f5;font-size:18px;line-height:1.6}.benefits{list-style:none;padding:0;margin:28px 0 0;display:grid;gap:18px}.benefits li{display:flex;gap:12px;align-items:flex-start}.benefits mat-icon{color:var(--pp-turquesa)}.benefits strong,.benefits small{display:block}.benefits small{color:#d9f5f5;margin-top:3px;line-height:1.4}.login__footer{margin-top:auto;color:#d9f5f5;font-size:13px}.login__form{display:grid;place-items:center;padding:32px}.form-card{width:min(100%,420px)}.brand{display:flex;align-items:center;gap:10px;color:var(--pp-marino)}.brand img{width:44px;height:44px}.brand div{display:flex;flex-direction:column}.brand span{color:var(--mat-sys-on-surface-variant);font-size:12px}.form-card h2{font-size:32px;margin:48px 0 4px}.form-card>p{color:var(--mat-sys-on-surface-variant);margin-bottom:28px}form{display:grid;gap:8px}.submit{height:48px}.submit mat-spinner{margin:auto}.error{display:flex;gap:8px;align-items:center;color:var(--pp-rojo);font-size:14px;margin:4px 0 8px}.help{color:var(--mat-sys-on-surface-variant);font-size:12px;text-align:center}@media(max-width:700px){.login{display:block}.login__brand{min-height:230px;padding:32px}.login__brand>img{width:52px;height:52px;margin-bottom:18px}.login__brand h1{font-size:32px}.login__brand>p:not(.eyebrow){font-size:15px}.login__footer{margin-top:28px}.login__form{padding:36px 24px}.form-card h2{margin-top:36px}}`],
})
export class LoginComponent {
	private readonly auth = inject(AuthService); private readonly router = inject(Router); private readonly fb = inject(FormBuilder);
	protected readonly cargando = signal(false); protected readonly error = signal('');
	protected readonly mostrarPassword = signal(false);
	protected readonly form = this.fb.nonNullable.group({ usuario: ['', Validators.required], password: ['', Validators.required] });
	protected entrar(): void { this.form.markAllAsTouched(); if (this.form.invalid) return; this.cargando.set(true); this.error.set(''); const { usuario, password } = this.form.getRawValue(); this.auth.login(usuario, password).subscribe({ next: () => void this.router.navigate(['/dashboard']), error: () => { this.error.set('Usuario o contraseña incorrectos'); this.cargando.set(false); } }); }
}
